// Generated by CoffeeScript 1.3.3

/*
  all damn scripts here
  18! by Alessio 'selfishl0v3' Zappa - http://www.alessiozappa.com
*/


(function() {

  if (Zepto.__proto__ === null) {
    document.getElementById('container').innerHTML = 'no way!';
  } else {
    Zepto(function($) {
      /* 
        detect mobile or not
      */

      var easing, interpolate;
      (function(a) {
        return $.browser.mobile = /android.+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|meego.+mobile|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(a) || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0, 4));
      })(navigator.userAgent || navigator.vendor || window.opera);
      if ($.browser.mobile) {
        if (!window.navigator.standalone) {
          $('#container').remove();
          $('#installMe').html('<span>Installami aggiungendomi alla tua homescreen!</span>').animate({
            top: (($('body').height() - $('#installMe').height()) / 2) - 80
          }, 500, 'ease-in-out');
        } else {
          $('#installMe').remove();
        }
      } else {
        $('#installMe').remove();
      }
      /* 
        scrollto zepto plugin from https://github.com/suprMax/ZeptoScroll
      */

      (function($) {});
      interpolate = function(source, target, shift) {
        return source + (target - source) * shift;
      };
      easing = function(pos) {
        return (-Math.cos(pos * Math.PI) / 2) + .5;
      };
      $.scroll = function(endY, duration, easingF) {
        var animate, finishT, startT, startY;
        endY = endY || ($.os.android ? 1 : 0);
        duration = duration || 200;
        (typeof easingF === "function") && (easing = easingF);
        startY = window.pageYOffset;
        startT = Date.now();
        finishT = startT + duration;
        animate = function() {
          var now, shift;
          now = +(new Date());
          shift = (now > finishT ? 1 : (now - startT) / duration);
          window.scrollTo(0, interpolate(startY, endY, easing(shift)));
          return (now > finishT) || setTimeout(animate, 15);
        };
        return animate();
      };
      /* 
        get photos
      */

      $.ajax({
        type: "GET",
        url: "js/photos.json",
        dataType: "json",
        success: function(data) {
          var i, loadImgs, obj;
          loadImgs = (function() {
            var _ref, _results;
            _ref = data["photos"];
            _results = [];
            for (i in _ref) {
              obj = _ref[i];
              _results.push($('div#pics').append("<img src=\"photos/" + obj["id"] + ".jpeg\" class=\"photo\" data-id=\"" + obj["id"] + "\" />"));
            }
            return _results;
          })();
          return $('.photo').on('click', function() {
            var current;
            current = $(this).attr('data-id');
            $('.photo').removeClass('active');
            $(this).addClass('active');
            return $('#text').animate({
              height: '0px'
            }, 500, 'ease-in-out', function() {
              var _ref, _results;
              $('#text').removeClass('open');
              _ref = data["photos"];
              _results = [];
              for (i in _ref) {
                obj = _ref[i];
                if (parseInt(obj["id"], 10) === parseInt(current)) {
                  $('span#photoNumber>span').text(obj["id"]);
                  $('span.desc').html(obj["didascalia"]);
                  $('#text').animate({
                    height: $('span.desc').height() + 20
                  }, 500, 'ease-in-out').addClass('open');
                  _results.push($.scroll(0, 500));
                } else {
                  _results.push(void 0);
                }
              }
              return _results;
            });
          });
        },
        error: function(xhr, type) {
          console.log(xhr);
          return console.log(type);
        }
      });
      $('.closeMe').on('click', function() {
        $('.photo').removeClass('active');
        return $('#text').animate({
          height: '1px'
        }, 500, 'ease-in-out', function() {
          $('span#photoNumber>span').text('');
          return $('span.desc').html('');
        }).removeClass('open');
      });
      return $(window).on("resize", function() {
        if ($('#text').hasClass('open')) {
          return $('#text').animate({
            height: $('span.desc').height() + 20
          }, 500, 'ease-in-out');
        }
      });
    });
  }

}).call(this);
